/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author javierarguedas
 */
public class personajes extends javax.swing.JFrame {

    /**
     * Creates new form personajes
     */
    public personajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Hansolo = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        chuvaca = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        Anakin = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        yoda = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JarJar = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        PrincesaLeia = new javax.swing.JLabel();
        BB8 = new javax.swing.JLabel();
        ANZOCATANO = new javax.swing.JLabel();
        DOCUS = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        DarthMaul = new javax.swing.JLabel();
        Grugu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PoeDamero = new javax.swing.JLabel();
        Wicket = new javax.swing.JLabel();
        Jabba = new javax.swing.JLabel();
        QuinGon = new javax.swing.JLabel();
        R2D2 = new javax.swing.JLabel();
        ObiWan = new javax.swing.JLabel();
        JynErso = new javax.swing.JLabel();
        KyloRen = new javax.swing.JLabel();
        FinnEasy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Han Solo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jButton20.setText("Qui Gon");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jButton18.setText("Yoda");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        jButton5.setText("Wicket");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        Hansolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/HAN_SOLO_Easy-Resize.com.jpg"))); // NOI18N
        Hansolo.setText("jLabel2");
        getContentPane().add(Hansolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 80, 120));

        jButton10.setText("Finn");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 80, 30));

        jButton19.setText("Grugu");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jButton17.setText("Chewbacca");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        chuvaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/chewbacca-star-wars-legends.jpg_242310155_Easy-Resize.com.jpg"))); // NOI18N
        chuvaca.setText("jLabel3");
        getContentPane().add(chuvaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, -1));

        jButton16.setText("Jyn Erso");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, -1, -1));

        jButton4.setText("Anakin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        jButton14.setText("Jabba");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        Anakin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Anakin_Skywalker_Easy-Resize.com.jpg"))); // NOI18N
        Anakin.setText("jLabel2");
        getContentPane().add(Anakin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, -1));

        jButton12.setText("BB-8");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jButton11.setText("R2D2");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        yoda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/yoda_Easy-Resize.com.jpg"))); // NOI18N
        yoda.setText("jLabel2");
        getContentPane().add(yoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 160, -1));

        jButton15.setText("Kylon Ren");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jButton8.setText("Princesa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jButton13.setText("Count Dookus");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        jButton7.setText("Ansoka");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jButton6.setText("Jar Jar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        JarJar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Jar Jar Binks_Easy-Resize.com.jpg"))); // NOI18N
        getContentPane().add(JarJar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jButton9.setText("Darth Maul");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        PrincesaLeia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Princesa Leia_Easy-Resize.com.jpg"))); // NOI18N
        PrincesaLeia.setText("jLabel2");
        getContentPane().add(PrincesaLeia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, -1));

        BB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/BB-8-_Easy-Resize.com.jpg"))); // NOI18N
        BB8.setText("jLabel2");
        getContentPane().add(BB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, -1));

        ANZOCATANO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/ahsoka-tano_Easy-Resize.com.jpg"))); // NOI18N
        ANZOCATANO.setText("jLabel2");
        getContentPane().add(ANZOCATANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));

        DOCUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/count_dookus-_Easy-Resize.com.jpg"))); // NOI18N
        DOCUS.setText("jLabel2");
        getContentPane().add(DOCUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 160, -1));

        jButton3.setText("Obi Wan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        DarthMaul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Darth Maul_Easy-Resize.com.jpg"))); // NOI18N
        DarthMaul.setText("jLabel2");
        getContentPane().add(DarthMaul, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, -1));

        Grugu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Grogu_Easy-Resize.com.jpg"))); // NOI18N
        Grugu.setText("jLabel2");
        getContentPane().add(Grugu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 160, -1));

        jButton2.setText("Poe ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 70, -1));

        PoeDamero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Poe Dameron_Easy-Resize.com.jpg"))); // NOI18N
        PoeDamero.setText("jLabel2");
        getContentPane().add(PoeDamero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 70, -1));

        Wicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Wicket_W._Easy-Resize.com.jpg"))); // NOI18N
        Wicket.setText("jLabel2");
        getContentPane().add(Wicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 80, -1));

        Jabba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Jabba el hutt_Easy-Resize.com.jpg"))); // NOI18N
        Jabba.setText("jLabel2");
        getContentPane().add(Jabba, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 150, -1));

        QuinGon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Quin Gon Jinn_Easy-Resize.com.jpg"))); // NOI18N
        QuinGon.setText("jLabel2");
        getContentPane().add(QuinGon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 160, -1));

        R2D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/R2D2_Easy-Resize.com.jpg"))); // NOI18N
        R2D2.setText("jLabel2");
        getContentPane().add(R2D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 160, -1));

        ObiWan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/obi-wan-kenobi_Easy-Resize.com.jpg"))); // NOI18N
        ObiWan.setText("jLabel2");
        getContentPane().add(ObiWan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, -1));

        JynErso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Jyn Erso_Easy-Resize.com.jpg"))); // NOI18N
        JynErso.setText("jLabel3");
        getContentPane().add(JynErso, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 160, -1));

        KyloRen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/KyloRen_Easy-Resize.com.jpg"))); // NOI18N
        KyloRen.setText("jLabel3");
        getContentPane().add(KyloRen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 160, -1));

        FinnEasy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/finn_Easy-Resize.com.jpg"))); // NOI18N
        FinnEasy.setText("jLabel3");
        getContentPane().add(FinnEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/Star-Wars-emblema_Easy-Resize.com.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Krungthep", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Personajes ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 410, 100));

        btnRegresar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starwars/imagenes/photo-1538370965046-79c0d6907d47.jpeg"))); // NOI18N
        jLabel1.setText("gon");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JOptionPane.showMessageDialog(null, "Especie: Humano\n"
        + "Genero: Masculino\n"
         + "Estatura: 1.8 Metros\n"
         + "Color  de Pelo: Castaño\n"
         + "Color de Ojos Cafe\n"
         + "Color de Piel: Clara\n"
         + "Han Solo era un arrogante corelliano con un ingenio sardónico, \n"
        + "humor seco, una disposición a veces imprudente, y \n"
        + "el sentido común tecnológico, que comenzó su carrera como contrabandista alrededor del año 10 ABY.\n"
        
        + "", "Han Solo",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 JOptionPane.showMessageDialog(null, "Especie: Humano\n"
        + "Genero: Masculino\n"
         + "Estatura: 1.72 Metros\n"
         + "Color  de Pelo: Maron\n"
         + "Color de Ojos Marron\n"
         + "Color de Piel: Clara\n"
         + "Poe Dameron fue un piloto humano que sirvió como comandante en la Nueva República\n"
         + " y, más tarde, la Resistencia durante su conflicto con la Primera Orden. "
        + "", "Poe Dameron",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       JOptionPane.showMessageDialog(null, "Fabricante: Industrias Automaton \n"
               
               + "Modelo: Unidad BB \n"
               + "Clase: Droide Astromecanico  \n"
               + "Color de sensor: Negro \n"
               + "BB-8[1] era un droide astromecánico de laserie BB La mayor parte de su cuerpo\n "
               + "estaba formado por una esfera metálica que le permitía rodar para desplazarse, \n"
               + "en su mayoría era de color blanco con algunos tonos naranja, tenía una cabeza en \n"
               + "forma de domo parecida al de un droide astromecánico serie R2, en donde tenía un\n"
               + " fotorreceptor negro. El droide perteneció al piloto Poe Dameron de la Resistencia \n"
               
           
                + "", "BB- 8\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
   JOptionPane.showMessageDialog(null, "Especie: Wookiee\n"
        + "Genero: Masculino\n"
         + "Estatura: 2.25 Metros\n"
         + "Color  de Pelo: Marron \n"
         + "Color de Ojos Negros \n"
         + "Planeta: Kashyyk\n"
         + "Chewbacca (o Chewie, como le decían sus amigos) era un legendario wookiee de Kashyyyk y \n"
           + "copiloto de la nave de Han Solo, el Halcón Milenario. Era el hijo de Attichitcuk, el esposo \n"
           + "de Mallatobuck y el padre de Lumpawaroo. Chewbacca llevaba consigo el nombre del antiguo héroe \n"
           + "wookiee, el gran Bacca, el primero de los grandes caciques de Kashyyyk, y el creador de una espada \n"
           + "que indicaba el liderazgo entre los wookiees. Este nombre indicaba que Chewbacca pertenecía a un noble\n "
           + "linaje, lo que fue corroborado por su rol en Kashyyyk durante las Guerras Clon y durante \n"
           + "la Guerra Civil Galáctica.\n" +
"\n "
               
         
        + "", "Chewbacca",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
  JOptionPane.showMessageDialog(null, "Especie: Especie de Yoda \n"
                + "Genero: Masculino \n"
                + "estatura: 0,34 metros  \n"
                + "Color  de Pelo: Blanco \n"
                + "Color de Ojos: Verde- Dorado \n"
                + "Color de Piel: Verde \n"
                + "Grogu, conocido por muchos simplemente como el Niño, fue un Iniciado Jedi y expósito\n"
          + " mandaloriano sensible a la Fuerza que pertenecía a la misma especie del Gran Maestro Jedi Yoda y \n"
          + "la Maestra Jedi Yaddle. Grogu nació alrededor de 41 ABY, y fue criado en el Templo Jedi en Coruscant. \n"
               
                + "", "Grogu \n",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Especie: Humano\n"
        + "Genero: Masculino\n"
         + "Estatura: 1.82 Metros\n"
         + "Color  de Pelo: Castaño Rojizo\n"
         + "Color de Ojos Griz-Azul\n"
         + "Color de Piel: Clara\n"
         + "Obi-Wan Kenobi fue un legendario Maestro Jedi humano que sirvió en el Alto Consejo\n "
                + "Jedi durante los últimos añosde la Era de la República. Como General Jedi, Kenobi\n"
                + " sirvió en el Gran Ejército de la República durante las Guerras Clon. Kenobi, sin embargo,\n "
                + "se vio obligado a exiliarse como resultado de la Gran Purga Jedi. Como mentor, Kenobi fue\n "
                + "responsable del entrenamiento de dos miembros de la familia Skywalker, Anakin Skywalker y\n "
                + "Luke Skywalker, sirviendo ambos como su Padawan para aprender los caminos de la Fuerza.\n"
         
        + "", "Obi-Wan Kenobi",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          JOptionPane.showMessageDialog(null, "Especie: Humano\n"
        + "Genero: Masculino\n"
         + "Estatura: 1.88 (2.03 con armadura) Metros\n"
         + "Color  de Pelo: Ribio a Castaño Luego pelon \n"
         + "Color de Ojos Azul - Amarillo \n"
         + "Color de Piel: Clara - luego Palida \n"
         + "Anakin Skywalker, un hombre humano sensible a la Fuerza, fue un Caballero Jedi de la República Galáctica\n "
                  + "y el Elegido de la Fuerza. Durante las Guerras Clon, sus logros como comandante en el campo de batalla \n"
                  + "le valieron el apodo del Héroe Sin Miedo. Después de pasar al lado oscuro de la Fuerza, se hizo conocido\n "
                  + "como Darth Vader, un Señor Oscuro de los Sith y aprendiz del Emperador Darth Sidious. Como Lord Sith,\n "
                  + "Vader se volvió contra sus antiguos camaradas y dió caza a los Jedi sobrevivientes hasta su casi extinción.\n "
                  + "Se convirtió en un ejecutor del Imperio Galáctico, que trabajó para aplastar a la Alianza para Restaurar \n"
                  + "la República por oponerse a la voluntad de su Maestro Sith. Sin embargo, a pesar de sus acciones como\n "
                  + "Darth Vader, un destello del lado luminoso de la Fuerza permaneció dentro del antiguo Anakin Skywalker.\n" +
"\n "
               
                + "", "Anakin Skywalker",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
                  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
                                              
        JOptionPane.showMessageDialog(null, "Especie: Bipeda \n"
                + "Planeta:Endor\n"
                + "Estatura: 1 Metron"
                + "Color  de Pelo: Diferentes tonalidades de negro, marrón, gris y blanco\n"
                + "Distinciones: Peludos, bajos de estatura, agudo sentido del olfato\n"
                + "Idioma:Ewokes\n"
                + "Los ewoks eran una especie bípeda, peluda y de pequeña estatura que abundaba en los \n"
                + "árboles de la boscosa luna de Endor. Poseían una tecnología primitiva pero aun así fueron vitales\n "
                + "para la victoria de los rebeldes en la Batalla de Endor.\n "
               
                +  "","Ewok",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(null, "Especie: Gungan\n"
                + "Genero: Masculino\n"
                + "Estatura: 1.96 \n"
                + "Color de Ojos Naranja \n"
                + "Planeta Natal: Naboo \n"
                + "Jar Jar Binks fue el primer gungan en representar a su pueblo en el Senado Galáctico,\n"
                + " primero como representante menor junto a la senadora Padmé Amidala y después de su muerte \n"
                + "como senador. Como la mayoría de los gungans, Jar Jar hablaba básico con un acento característico.\n"
                + " A pesar de ser ingenuo, inútil, estúpido y patoso, Jar Jar Binks contribuyó enormemente al sino de\n "
                + "la República Galáctica, para bien y para mal.\n "
                
                +  "","Jar Jar Binks",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
          JOptionPane.showMessageDialog(null, "Especie: Togruta\n"
        + "Genero: Femenino\n"
         + "Estatura: 1.88\n"
        
         + "Color de Ojos: Azul  \n"
         + "Color de Piel: Naranja \n"
         + "Ahsoka Tano, apodada por su Maestro como «Sabionda», «Chulita» o «Mocosa», fue una Padawan\n "
                  + "Jedi togruta que, tras las Guerras Clon, ayudó a establecer una red de células rebeldes\n"
                  + " para combatir al Imperio Galáctico. Tano fue descubierta en su planeta natal Shili por\n "
                  + "el Maestro Jedi Plo Koon, quien la llevó al Templo Jedi de Coruscant para que fuese entrenada \n"
                  + "en las artes Jedi. Después del estallido de las Guerras Clon, el Gran Maestro Jedi Yoda asignó \n"
                  + "a la joven Tano como Padawan del Caballero Jedi Anakin Skywalker, a quien se unió durante la Batalla\n "
                  + "de Christophsis.\n "
                  
               
                + "", "Ahsoka Tano",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     JOptionPane.showMessageDialog(null, "Especie: Humano\n"
        + "Genero: Femenin \n"
         + "Estatura: 1.55 \n"
         + "Color  de Pelo: Castaño \n"
         + "Color de Ojos: Castaños \n"
         + "Planeta:Alderaan \n"
         + "Leia Organa Solo (nacida Leia Amidala Skywalker) fue en diversas etapas de su vida política,\n "
             + "revolucionaria y Caballero Jedi de la Nueva Orden Jedi. Hija del General Jedi Anakin Skywalker\n"
             + " y la senadora Padmé Amidala de Naboo, Leia fue la hermana melliza de Luke Skywalker, y poco \n"
             + "después de su nacimiento se convirtió en la hija adoptiva de Bail Prestor Organa y la reina \n"
             + "Breha Antilles Organa de Alderaan, convirtiéndola en princesa de Alderaan. Una senadora consumada,\n"
             + " Leia fue famosa por su fuerte liderazgo durante la Guerra Civil Galáctica y otros conflictos galácticos\n "
             + "posteriores, haciéndola uno de los héroes más grandes de la galaxia. \n "
              
               
                + "", "Leia Organa Solo\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       JOptionPane.showMessageDialog(null, "Especie: Zabrak \n"
        + "Genero: Mascuino \n"
         + "Estatura: 1.94 \n"
         + "Color  de Pelo: Castaño \n"
         + "Color de Ojos: Amarillo y Rojo \n"
         + "Planeta:Dathoir \n"
         + "Maul fue un zabrak dathomiriano sensible a la Fuerza y un guerrero del lado oscuro que sirvió\n "
               + "como el aprendiz Señor Oscuro de los Sith Darth Maul durante los últimos años de la\n "
               + "República Galáctica y reinó como señor del crimen durante el dominio del Imperio Galáctico.\n "
               + "El hijo de la Madre Talzin de las Hermanas de la Noche, Maul fue tomado a una edad temprana por \n"
               + "el Señor Oscuro de los Sith Darth Sidious, quien lo ungió como su primer aprendiz Sith, Darth Maul.\n "
               + "Gracias a su entrenamiento, Maul se hizo fuerte en el lado oscuro de la Fuerza, convirtiéndose en un \n"
               + "duelista y asesino experto que anhelaba revelar la continuada supervivencia de los Sith a la Orden Jedi. \n "
           
                + "", "Darth Maul\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png")); 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 JOptionPane.showMessageDialog(null, "Especie: Humano \n"
        + "Genero: Mascuino \n"
         + "Estatura: 1.78 \n"
         + "Color  de Pelo: Negro \n"
         + "Color de Ojos: Cafe  \n"
         + "Color de Piel: Oscura  \n"
         + "Finn fue el apodo de FN-2187 (Ocho-Siete), un soldado de asalto humano sensible a la Fuerza que sirvió\n"
               + " a la Primera Orden hasta su huida y posterior deserción a la Resistencia durante la Guerra Primera\n "
               + "Orden-Resistencia. Aunque entrenado desde el nacimiento para ser un soldado leal y obediente,\n "
               + "la conciencia de FN-2187 entró en conflicto con los métodos de la Primera Orden. Durante un \n"
               + "tiempo no estuvo dispuesto a apoyar a la Resistencia, con la esperanza de escapar del conflicto\n "
               + "galáctico en lugar de luchar por una causa que creía estaba condenada al fracaso. A medida que\n "
               + "la galaxia se consumía por la guerra, el soldado renegado se vio finalmente obligado a decidir \n"
               + "dónde estaban sus verdaderas lealtades.\n "
               
           
                + "", "Finn\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
JOptionPane.showMessageDialog(null, "Fabricante: Industrias Automaton \n"
               + "Linea de Producto: Serie R \n"
               + "Estatura: 1.08 \n"
               + "Modelo Droide Astromecanico Serie R \n"
               + "Genero: Programacon Masculina  \n"
               + "Color de sensor: Rojo \n"
               + "R2-D2, pronunciado Artoo-Deetoo/Erredós-Dedós y a menudo referido como R2 (Artoo/Erredós), \n"
               + "fue un droide astromecánico serie R2 manufacturado por Industrias Automaton con programación \n"
               + "masculina. Un ingenioso y valiente droide, R2-D2 sirvió a una multitud de maestros a lo largo \n"
               + "de su vida. R2 nunca recibió un borrado completo de memoria ni recibió programación nueva,\n "
               + "lo que resultó en su actitud aventurera e independiente. A menudo viéndose implicado en\n "
               + "momento vitales de la historia galáctica, su valentía e ingenio salvaron a la galaxia repetidas veces.\n"
           
                + "", "R2-D2\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
   
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    JOptionPane.showMessageDialog(null, "Especie: Humano\n"
            + "Genero: Masculino \n"
            + "Estatura: 1.96 \n"
            + "Color  de Pelo: Castaño Orcuro a Canoso  \n"
            + "Color de Ojos: Marrones \n"
            + "Planeta:Serenno \n"
            + "Dooku fue un Maestro Jedi que cayó al lado oscuro de la Fuerza, convirtiéndose entonces\n "
            + "en un Lord Oscuro de los Sith. Nacido en Serenno, fue el heredero del gran y prestigioso\n "
            + "título de Conde. Dooku fue tomado entonces por la Orden Jedi, como aprendiz a cargo de Thame\n "
            + "Cerulian. Una vez nombrado Caballero Jedi, tomó a Qui-Gon Jinn como su primer padawan.\n"
            + " Poco después, entrenaría a Komari Vosa. Dooku era respetado como un gran instructor en el\n "
            + "Templo Jedi, y como uno de los mejores duelistas de la galaxia. Únicamente los Maestros Yoda y\n "
            + "Mace Windu eran mas potentes al intelecto de Dooku.\n "
            + "", "Dooku\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      JOptionPane.showMessageDialog(null, "Especie: Hut\n"
              + "Genero: Hermafrodita \n"
              + "Estatura: 3.90 de largo \n"
              + "Color  de Pelo: no tiene \n"
              + "Color de Ojos: Naranjas \n"
              + "Planeta:Nal Hutta \n"
              + "Jabba Desilijic Tiure, mejor conocido como Jabba el Hutt, fue uno de los señores del\n "
              + "crimen hutt más conocidos en la galaxia, que gobernó un gran imperio criminal \n"
              + "localizado en los Territorios del Borde Exterior desde su palacio del desierto\n "
              + "en Tatooine. En el apogeo de su poder, Jabba fue uno de los señores del crimen más\n"
              + " poderosos de la galaxia, incluso tenía contacto con el Príncipe Xizor, el\n "
              + "líder del Sindicato Sol Negro.\n"
              + "\n " + "", "Jabba Desilijic Ticure\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      JOptionPane.showMessageDialog(null, "Especie: Humano \n"
        + "Genero: Mascuino \n"
         + "Estatura: 1.91 \n"
         + "Color  de Pelo: Negro \n"
         + "Color de Ojos: Cafe  \n"
         + "Color de Piel: Clara  \n"
         + "Kylo Ren no es un Sith\". Trabaja para el Líder Supremo Snoke, que es una \n"
              + "figura poderosa en el Lado Oscuro de la Fuerza.4​ Abrams le había dicho anteriormente\n"
              + "a Entertainment Weekly que el personaje \"tomó el nombre de Kylo Ren cuando se \n"
              + "unió a un grupo llamado Los Caballeros de Ren.\n"
             
                + "", "Finn\n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));   
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       JOptionPane.showMessageDialog(null, "Especie: Humano \n"
        + "Genero: Femenino \n"
       
         + "Color  de Pelo: Cafe \n"
         + "Color de Ojos: Cafe  \n"
         + "Color de Piel: Clara  \n"
         + "Jyn Erso es, en el universo de Star Wars, una soldado de la Alianza Rebelde.\n "
               + "Es la hija de Galen Erso. Fue soldado de la banda insurgente de Saw Gerrera,\n "
               + "un luchador rebelde onderoniano de las Guerras Clon. Nacida a comienzos de \n"
               + "las guerras clon, Jyn pasó la primera parte de su vida con Galen,\n "
               + "su padre, y Lyra Erso, su madre. Cuando ya era una adolescente \n"
               + "de 18 años, Jyn acabó sola nuevamente al ser abandonada por Saw.\n "
               + "Desde que Jyn fue raptada en Wobani, Saw pasó años atrincherado \n"
               + "en Jedha con sus guerreros. \n"
            
             
                + "", "Jyn Erso \n",
                      
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));  
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        JOptionPane.showMessageDialog(null, "Especie: Especie de Yoda \n"
                + "Genero: Masculino \n"
                + "estatura: 0,66 metros  \n"
                + "Color  de Pelo: Blanco \n"
                + "Color de Ojos: Verde- Dorado \n"
                + "Color de Piel: Verde \n"
                + "Yoda fue un miembro masculino de una especie misteriosa. \n"
                + "Era un reverenciado Maestro Jedi que sirvió como Gran Maestro de la \n"
                + "Orden Jedi en los últimos días de la República Galáctica. Era famoso dentro\n "
                + "de la Orden por su sabiduría, poderes de la Fuerza y combate con sables de luz,\n "
                + "y vivió durante casi 900 años. Su tiempo durante los últimos días de la Orden Jedi\n"
                + " y más allá lo convirtió en una figura consecuente en la historia galáctica.\n "
                + "", "Yoda \n",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      JOptionPane.showMessageDialog(null, "Especie: Humano \n"
                + "Genero: Masculino \n"
                + "estatura: 1,93 metros  \n"
                + "Color  de Pelo: Castaño \n"
                + "Color de Ojos: Azul \n"
                + "Color de Piel: Clara  \n"
                + "Qui-Gon Jinn, un hombre humano sensible a la Fuerza, fue un venerable y rebelde Maestro Jedi que vivió durante\n "
              + "los últimos años de la era de la República. Era un miembro sabio y respetado de la Orden Jedi, y se le ofreció un\n "
              + "asiento en el Consejo Jedi que él decidió rechazar para seguir su propio camino. Siguiendo una filosofía centrada \n"
              + "alrededor de la Fuerza Viva, Jinn se esforzó por seguir la voluntad de la Fuerza incluso cuando sus acciones \n"
              + "estaban en conflicto con los deseos del Consejo. Después de encontrarse con Anakin Skywalker, Jinn lo \n"
              + "llevó al Templo Jedi de Coruscant, convencido de que había encontrado al Elegido. Su último deseo fue \n"
              + "que Skywalker se convirtiera en un Jedi y que finalmente devolviera el equilibrio a la Fuerza. \n"
                + "", "Qui Gon \n",
                JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/joystick.png"));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
       this.dispose();
       FrmSobres s = new FrmSobres();
       s.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANZOCATANO;
    private javax.swing.JLabel Anakin;
    private javax.swing.JLabel BB8;
    private javax.swing.JLabel DOCUS;
    private javax.swing.JLabel DarthMaul;
    private javax.swing.JLabel FinnEasy;
    private javax.swing.JLabel Grugu;
    private javax.swing.JLabel Hansolo;
    private javax.swing.JLabel Jabba;
    private javax.swing.JLabel JarJar;
    private javax.swing.JLabel JynErso;
    private javax.swing.JLabel KyloRen;
    private javax.swing.JLabel ObiWan;
    private javax.swing.JLabel PoeDamero;
    private javax.swing.JLabel PrincesaLeia;
    private javax.swing.JLabel QuinGon;
    private javax.swing.JLabel R2D2;
    private javax.swing.JLabel Wicket;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel chuvaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel yoda;
    // End of variables declaration//GEN-END:variables
}
